// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzpyqwuopxngnvcffsvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6cHlxd3VvcHhuZ252Y2Zmc3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNDIyMzAsImV4cCI6MjA2NjcxODIzMH0.vFDlcMYRAzl85iUTLhNgIk-1eyZeO5lldn8SiaGt9vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});